### ISSUE TITLE
[NSA] Model Architecture

### ISSUE THREAD

**Issue by egnaf** [reckue/post-service-api#11]
Please, provide model architecture before writing code.

**Comment by Hardelele** [comment]
Explain me how you want to i did it.

**Comment by egnaf** [comment]
> Explain me how you want to i did it.

Provide me the architecture diagram of models of the service.

**Comment by Hardelele** [comment]
How could i did it?

**Comment by egnaf** [comment]
First, draw all the models and their relationships on the diagram.

> How could i make it?

**Comment by Hardelele** [comment]
https://media.discordapp.net/attachments/693510458958938125/706899817934356550/unknown.png?width=951&height=660
